AWSTemplateFormatVersion: "2010-09-09"
Description: "ECS Web POC Project"
Parameters:
  ProjectName:
    Type: String
    Description: Project Name
  EnvironmentName:
    Type: String
    Description: Environment Name

Resources:
    ECRRepositoryWeb:
      Type: 'AWS::ECR::Repository'
      Properties:
        RepositoryName: !Sub "${ProjectName}/${EnvironmentName}/web"
        ImageTagMutability: MUTABLE   
        LifecyclePolicy:
          LifecyclePolicyText: arn:aws:iam::aws:policy/PowerUserAccess                     

    ECRRepositoryApi:
      Type: 'AWS::ECR::Repository'
      Properties:
        RepositoryName: !Sub "${ProjectName}/${EnvironmentName}/api"
        ImageTagMutability: MUTABLE   
        LifecyclePolicy:
          LifecyclePolicyText: arn:aws:iam::aws:policy/PowerUserAccess                     

