AWSTemplateFormatVersion: "2010-09-09"
Description: ""
Parameters:
  ProjectName:
    Type: String
    Description: Project Name
  EnvironmentName:
    Type: String
    Description: Environment Name
Resources:
    EC2Instance:
        Type: "AWS::EC2::Instance"
        Properties:
            ImageId: "ami-024e6efaf93d85776"
            InstanceType: "t2.micro"
            KeyName: "danilotessleraws1"
            AvailabilityZone: !Sub "${AWS::Region}c"
            Tenancy: "default"
            SubnetId: "subnet-0a0a9c6b037524e02"
            EbsOptimized: false
            SecurityGroupIds: 
              - "sg-0ea5f1e49210fadd9"
              - "sg-0eac2d5570f3355e8"
            SourceDestCheck: true
            BlockDeviceMappings: 
              - 
                DeviceName: "/dev/sda1"
                Ebs: 
                    Encrypted: false
                    VolumeSize: 8
                    SnapshotId: "snap-07592d65a6f259c5b"
                    VolumeType: "gp2"
                    DeleteOnTermination: true
            IamInstanceProfile: "AmazonSSMRoleForInstancesQuickSetup"
            Tags: 
              - 
                Key: "Name"
                Value: !Join [ "_", [ !Ref ProjectName, !Ref EnvironmentName, "EC2"] ]